const ICONS={接送:'🚐',飯店:'🏨',餐飲:'🍽️',親子:'🧒',休息:'🛏️',景點:'📍',地鐵:'🚇',轉乘:'↔️',JR:'🚆',交通:'🚌',購物:'🛍️',拍照:'📸',包車:'🚐',機場:'✈️',航班:'🛫',備案:'☂️'};
const SCHEMA_VERSION=4, APP_KEY='tino-travel-v4-data', LEGACY_DONE='tino-fukuoka-v3-migrated', WEATHER_KEY='tino-travel-weather-v1';
const LEGACY_ITINERARY_KEY='tino-fukuoka-trip-itinerary-v1', LEGACY_PROGRESS_KEY='tino-fukuoka-trip-progress-v2', LEGACY_DAY_KEY='tino-fukuoka-current-day', EDIT_KEY='tino-fukuoka-edit-mode';
const TRAVEL_MODE={接送:'driving',包車:'driving',地鐵:'transit',JR:'transit',轉乘:'transit',交通:'transit'};
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0, coordNum=v=>v===''||v===null||v===undefined?null:num(v), clone=v=>JSON.parse(JSON.stringify(v));
const uid=(p='id')=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
const safeJson=(t,f=null)=>{try{return JSON.parse(t)||f}catch{return f}};
const {hasCoord,haversineKm,formatDistance,stableTimeSort}=window.ItineraryCore;
const coord=s=>`${Number(s.lat)},${Number(s.lng)}`, searchUrl=s=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name||coord(s))}`;
const routeUrl=(a,b)=>hasCoord(a)&&hasCoord(b)?`https://www.google.com/maps/dir/?api=1&origin=${coord(a)}&destination=${coord(b)}&travelmode=${TRAVEL_MODE[b.type]||'walking'}`:'';
const dayRouteUrl=d=>{const s=(d?.stops||[]).filter(hasCoord);return s.length?`https://www.google.com/maps/dir/?api=1&origin=${coord(s[0])}&destination=${coord(s.at(-1))}&waypoints=${s.slice(1,-1).map(coord).join('%7C')}&travelmode=transit`:'https://www.google.com/maps';};
let appData=loadAppData(), editMode=localStorage.getItem(EDIT_KEY)==='true', map=null, markers=[], routeLine=null, deferredPrompt=null, pendingUndo=null, undoTimer=null, editingStopId=null, placeSearchTimer=null, placeSearchController=null, fallbackSearchAt=0, weatherRequest=null, weatherCache=safeJson(localStorage.getItem(WEATHER_KEY),{});
function defaultTrip(){return normalizeTrip({id:uid('trip'),brandLine:'TINO FAMILY TRIP · FUKUOKA',title:'福岡三代同堂\n無礙動線',subtitle:'5 大 1 小｜推車｜長輩可休｜單區規劃',members:'Tino、潘婷、爸爸、媽媽、岳母、嘟嘟（3 歲）',city:'福岡',dateRange:'8/20–8/26',startDate:'2026-08-20',hotel:'三井花園飯店福岡中洲',nights:'6 晚同飯店',tags:'長輩可休, 推車優先, 雨天備案',themeColor:'#173f73',days:clone(window.DEFAULT_ITINERARY||[]),progress:{},currentDayId:localStorage.getItem(LEGACY_DAY_KEY)||1});}
function normalizeStop(s,i){return {id:String(s.id||uid('stop')),time:String(s.time||''),name:String(s.name||`景點 ${i+1}`),type:String(s.type||'景點'),lat:coordNum(s.lat),lng:coordNum(s.lng),note:String(s.note||''),transport:String(s.transport||''),duration:String(s.duration||''),elder:String(s.elder||''),kid:String(s.kid||''),backup:String(s.backup||''),mapUrl:String(s.mapUrl||''),expense:Math.max(0,Math.round(num(s.expense)))};}
function normalizeDay(d,i){return {id:String(d.id||uid('day')),date:String(d.date||''),title:String(d.title||`Day ${i+1}`),theme:String(d.theme||''),area:String(d.area||''),center:Array.isArray(d.center)?[num(d.center[0]),num(d.center[1])]:[33.5902,130.4017],stops:(d.stops||[]).map(normalizeStop),autoSort:d.autoSort!==false};}
function normalizeTrip(t){const days=(t.days||t.itinerary||[]).map(normalizeDay);return {id:String(t.id||uid('trip')),brandLine:String(t.brandLine||''),title:String(t.title||'新旅行'),subtitle:String(t.subtitle||''),members:String(t.members||''),city:String(t.city||''),dateRange:String(t.dateRange||''),startDate:String(t.startDate||(t.city==='福岡'?'2026-08-20':'')),hotel:String(t.hotel||''),nights:String(t.nights||''),tags:String(t.tags||''),themeColor:String(t.themeColor||'#173f73'),days:days.length?days:[normalizeDay({title:'新行程日',stops:[]},0)],progress:t.progress&&typeof t.progress==='object'?t.progress:{},currentDayId:String(t.currentDayId||days[0]?.id||'')};}
function normalizeAppData(v){const trips=(v?.trips||[]).map(normalizeTrip);return {schemaVersion:SCHEMA_VERSION,currentTripId:String(v?.currentTripId||trips[0]?.id||''),trips:trips.length?trips:[defaultTrip()]};}
function migrateLegacy(){if(localStorage.getItem(LEGACY_DONE)==='true')return null;const legacy=safeJson(localStorage.getItem(LEGACY_ITINERARY_KEY),null), progress=safeJson(localStorage.getItem(LEGACY_PROGRESS_KEY),{});const trip=defaultTrip(); if(legacy)trip.days=legacy.map(normalizeDay); trip.progress=Object.fromEntries(Object.entries(progress||{}).map(([k,v])=>[k.split(':').length===2?`${trip.id}:${k}`:k,v])); trip.currentDayId=String(localStorage.getItem(LEGACY_DAY_KEY)||trip.days[0]?.id); localStorage.setItem(LEGACY_DONE,'true'); return {schemaVersion:SCHEMA_VERSION,currentTripId:trip.id,trips:[trip]};}
function loadAppData(){const saved=safeJson(localStorage.getItem(APP_KEY),null); if(saved?.schemaVersion===SCHEMA_VERSION)return normalizeAppData(saved); const migrated=migrateLegacy(); const data=migrated||{schemaVersion:SCHEMA_VERSION,currentTripId:'',trips:[defaultTrip()]}; localStorage.setItem(APP_KEY,JSON.stringify(data)); return normalizeAppData(data);}
function setAppStatus(text,tone='saved',delay=1800){const el=$('appStatus');if(!el)return;el.textContent=text;el.dataset.tone=tone;clearTimeout(setAppStatus.timer);if(delay)setAppStatus.timer=setTimeout(()=>{if(navigator.onLine){el.textContent='✓ 已儲存';el.dataset.tone='saved';}},delay);}function save(){localStorage.setItem(APP_KEY,JSON.stringify(appData));setAppStatus('✓ 已儲存','saved');}
function trip(){return appData.trips.find(t=>t.id===appData.currentTripId)||appData.trips[0];}
function day(){const t=trip();return t.days.find(d=>String(d.id)===String(t.currentDayId))||t.days[0];}
const pkey=(d,s)=>`${trip().id}:${d}:${s}`;
function renderAll(skipSettings=false){renderHero();renderTabs();renderHome();renderDay();if(!skipSettings)renderSettings();document.body.classList.toggle('edit-mode',editMode);refreshWeather();}
function renderHero(){const t=trip();document.documentElement.style.setProperty('--navy',t.themeColor||'#173f73');$('brandLine').textContent=t.brandLine;$('heroTitle').innerHTML=esc(t.title).replace(/\n/g,'<br>');$('heroSubtitle').textContent=t.subtitle;$('tripFacts').innerHTML=[t.dateRange,t.nights,t.city].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');$('tripSelect').innerHTML=appData.trips.map(x=>`<option value="${esc(x.id)}" ${x.id===t.id?'selected':''}>${esc(x.title.replace(/\n/g,' '))}</option>`).join('');}
function renderTabs(){const t=trip();$('dayTabs').innerHTML=t.days.map((d,i)=>`<button class="day-tab ${d.id===String(t.currentDayId)?'active':''}" data-day="${esc(d.id)}"><b>Day ${i+1}</b><small>${esc((d.date||'').split(' ')[0])}</small></button>`).join('')+(editMode?'<button class="day-tab add-day" id="addDay">＋新增</button>':'');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{t.currentDayId=b.dataset.day;save();renderAll();switchView('scheduleView');});$('addDay')?.addEventListener('click',addDay);}
function tripExpense(t=trip()){return t.days.reduce((sum,d)=>sum+d.stops.reduce((n,s)=>n+num(s.expense),0),0);}function dayExpense(d=day()){return (d?.stops||[]).reduce((sum,s)=>sum+num(s.expense),0);}const yen=value=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(num(value));
function renderHome(){$('homePanel').innerHTML='';}
function sortDay(d){if(d.autoSort)d.stops=stableTimeSort(d.stops);}
function renderDay(){const t=trip(),d=day();if(!d)return;sortDay(d);$('daySummary').innerHTML=`<article class="summary-card journey-summary"><div class="journey-heading"><p class="date-line">${esc(d.date)} · DAY ${t.days.indexOf(d)+1}${d.area?` · ${esc(d.area)}`:''}</p><h2>${esc(d.title)}</h2></div><div class="weather-row" id="dayWeather"><span>🌤 天氣載入中…</span></div><div class="journey-metrics"><span>📍 ${d.stops.length} 站</span><span>💴 ${yen(dayExpense(d))}</span></div>${editMode?dayEditor(d,t):''}</article>`;$('timeline').innerHTML=d.stops.map((s,i)=>`${i?travelInfo(d.stops[i-1],s):''}${stopCard(d,s,i)}`).join('')+`<button class="add-stop-fixed" id="quickAddStop">＋ 新增景點</button>`;bindEditors(d);$('openDayMap').href=dayRouteUrl(d);updateMap(d);}
function dayEditor(d,t){return `<div class="editor-panel day-editor"><label class="sort-toggle"><input type="checkbox" id="autoSort" ${d.autoSort!==false?'checked':''}>依時間自動排序</label><label>日期<input data-day-field="date" value="${esc(d.date)}"></label><label>每日主題<input data-day-field="title" value="${esc(d.title)}"></label><label>區域<input data-day-field="area" value="${esc(d.area)}"></label><label class="wide">說明<textarea data-day-field="theme">${esc(d.theme)}</textarea></label><div class="edit-actions"><button class="edit-btn primary" id="addStop">＋新增景點</button><button class="edit-btn" id="copyDay">複製本日</button><button class="edit-btn" id="dayUp">↑ 日期上移</button><button class="edit-btn" id="dayDown">↓ 日期下移</button><button class="edit-btn danger" id="deleteDay">刪除本日</button></div></div>`;}
function transportIcon(s){const v=`${s.transport||''} ${s.type||''}`;return v.includes('地鐵')?'🚇':v.includes('JR')?'🚆':v.includes('巴士')||v.includes('交通')?'🚌':v.includes('包車')?'🚐':v.includes('接送')?'🚐':'🚶';}
function travelInfo(a,b){const km=haversineKm(a,b),distance=formatDistance(km),route=routeUrl(a,b);return route?`<a class="travel-info" href="${route}" target="_blank" rel="noopener">${transportIcon(b)} ${distance}${b.duration?`｜約 ${esc(b.duration)}`:''}<small>直線距離 · 開啟 Google Maps</small></a>`:`<div class="travel-info unavailable">${transportIcon(b)} ${distance}<small>直線距離</small></div>`;}
function stopCard(d,s,i){const done=trip().progress[pkey(d.id,s.id)],prev=d.stops[i-1];return `<article class="stop-card ${done?'done':''}" data-index="${i}" data-stop-id="${esc(s.id)}"><div class="stop-icon">${ICONS[s.type]||'•'}</div><div class="stop-header"><div><div class="stop-time">${esc(s.time)} <span class="stop-type">｜${esc(s.type)}</span></div><h3 class="stop-name">${esc(s.name)}</h3></div><button class="complete" data-complete="${esc(s.id)}">✓</button></div><p class="stop-note">${esc(s.note)}</p>${i?`<div class="travel-note">${esc(s.transport||'從上一站前往')} ${s.duration?`· ${esc(s.duration)}`:''}</div>`:''}<div class="badges"><span class="badge elder">長輩｜${esc(s.elder)}</span><span class="badge kid">嘟嘟｜${esc(s.kid)}</span>${s.backup?`<span class="badge backup">備案｜${esc(s.backup)}</span>`:''}${num(s.expense)>0?`<span class="badge expense">實付｜${yen(s.expense)}</span>`:''}</div><div class="actions"><a class="action map" href="${searchUrl(s)}" target="_blank" rel="noopener">📍 查看地點</a>${prev&&routeUrl(prev,s)?`<a class="action route" href="${routeUrl(prev,s)}" target="_blank" rel="noopener">🧭 從上一站導航</a>`:''}<button class="action quick-action" data-quick-edit type="button">✏️ 編輯</button><button class="action quick-action danger" data-quick-delete type="button">🗑️ 刪除</button></div>${editMode?stopEditor(s,i,d.stops.length):''}</article>`;}
function stopEditor(s,i,total){const input=(f,l)=>`<label>${l}<input ${f==='time'?'type="time"':''} data-stop-field="${f}" value="${esc(s[f])}"></label>`;return `<div class="editor-panel stop-editor">${input('time','時間')}${input('name','名稱')}<label>類型<input list="typeList" data-stop-field="type" value="${esc(s.type)}"></label>${input('transport','交通')}${input('duration','移動')}${input('expense','實際花費（日圓）')}${input('lat','緯度')}${input('lng','經度')}<label class="wide">說明<textarea data-stop-field="note">${esc(s.note)}</textarea></label>${input('elder','長輩')}${input('kid','幼兒')}<label class="wide">備案<input data-stop-field="backup" value="${esc(s.backup)}"></label><div class="edit-actions"><button class="edit-btn" data-copy-stop>複製</button><button class="edit-btn" data-move="up" ${i===0?'disabled':''}>↑ 上移</button><button class="edit-btn" data-move="down" ${i===total-1?'disabled':''}>↓ 下移</button><button class="edit-btn danger" data-delete-stop>刪除</button></div></div>`;}
function bindEditors(d){document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const k=pkey(d.id,b.dataset.complete);trip().progress[k]=!trip().progress[k];if(!trip().progress[k])delete trip().progress[k];save();renderDay();});$('quickAddStop').onclick=()=>openStopSheet();document.querySelectorAll('.stop-card').forEach(card=>{const s=d.stops[Number(card.dataset.index)];card.querySelector('[data-quick-edit]')?.addEventListener('click',()=>openStopSheet(s));card.querySelector('[data-quick-delete]')?.addEventListener('click',()=>{if(confirm(`刪除「${s.name}」？`))deleteStopWithUndo(d,s,Number(card.dataset.index));});});if(!editMode)return;document.querySelectorAll('[data-day-field]').forEach(el=>el.oninput=()=>{d[el.dataset.dayField]=el.value;save();renderHero();renderTabs();updateMap(d);});$('addStop').onclick=openStopSheet;$('autoSort').onchange=e=>{d.autoSort=e.target.checked;sortDay(d);save();renderDay();};$('copyDay').onclick=()=>{const c=clone(d);c.id=uid('day');c.stops=c.stops.map(s=>({...s,id:uid('stop')}));trip().days.splice(trip().days.indexOf(d)+1,0,c);trip().currentDayId=c.id;save();renderAll();};$('deleteDay').onclick=deleteDay;$('dayUp').onclick=()=>moveDay(-1);$('dayDown').onclick=()=>moveDay(1);document.querySelectorAll('.stop-card').forEach(card=>{const s=d.stops[Number(card.dataset.index)];card.querySelectorAll('[data-stop-field]').forEach(el=>el.onchange=()=>{s[el.dataset.stopField]=['lat','lng'].includes(el.dataset.stopField)?coordNum(el.value):el.dataset.stopField==='expense'?Math.max(0,Math.round(num(el.value))):el.value;save();renderDay();});card.querySelector('[data-copy-stop]')?.addEventListener('click',()=>{const c={...clone(s),id:uid('stop')};d.stops.splice(Number(card.dataset.index)+1,0,c);save();renderDay();});card.querySelector('[data-delete-stop]')?.addEventListener('click',()=>{deleteStopWithUndo(d,s,Number(card.dataset.index))});card.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveStop(Number(card.dataset.index),b.dataset.move));});}
function renderSettings(){const t=trip(),field=(f,l)=>`<label>${l}<input data-trip-field="${f}" value="${esc(t[f])}"></label>`;$('settingsPanel').innerHTML=`<div class="editor-panel settings-editor">${field('brandLine','品牌列')}<label>主題顏色<input type="color" data-trip-field="themeColor" value="${esc(t.themeColor)}"></label><label class="wide">主標題<textarea data-trip-field="title">${esc(t.title)}</textarea></label>${field('subtitle','副標題')}${field('members','成員摘要')}${field('city','城市')}${field('dateRange','日期')}${field('startDate','旅行開始日（YYYY-MM-DD）')}${field('hotel','飯店')}${field('nights','住宿晚數')}${field('tags','標籤')}<div class="edit-actions"><button class="edit-btn danger" id="deleteTrip">刪除旅行</button></div></div><div class="data-tools"><button class="reset-button primary" id="exportTrip">匯出單一旅行</button><button class="reset-button primary" id="importTrip">匯入單一旅行</button><button class="reset-button primary" id="backupAll">完整備份</button><button class="reset-button" id="restoreDefault">恢復原始福岡行程</button><button class="reset-button" id="resetProgress">清除本旅行完成紀錄</button></div>`;document.querySelectorAll('[data-trip-field]').forEach(el=>el.oninput=()=>{t[el.dataset.tripField]=el.value;save();renderHero();renderHome();});$('deleteTrip').onclick=deleteTrip;$('exportTrip').onclick=()=>downloadJson(`${t.city||'trip'}-v4.json`,t);$('backupAll').onclick=()=>downloadJson('tino-travel-v4-backup.json',appData);$('importTrip').onclick=()=>$('importFile').click();$('restoreDefault').onclick=()=>{if(confirm('恢復原始福岡行程？')){const n=defaultTrip();Object.assign(t,n,{id:t.id,progress:{}});save();renderAll();}};$('resetProgress').onclick=()=>{if(confirm('清除本旅行完成紀錄？')){t.progress={};save();renderAll(true);}};}
function addDay(){const t=trip(),d=normalizeDay({id:uid('day'),date:'新日期',title:'新行程日',theme:'請輸入今日主題。',stops:[]},t.days.length);t.days.push(d);t.currentDayId=d.id;save();renderAll();}
function moveDay(delta){const t=trip(),i=t.days.indexOf(day()),to=i+delta;if(to<0||to>=t.days.length)return;[t.days[i],t.days[to]]=[t.days[to],t.days[i]];save();renderAll();}
function deleteDay(){const t=trip(),d=day();if(t.days.length<=1)return alert('至少需保留一天。');if(confirm('刪除本日與所有景點？')){t.days=t.days.filter(x=>x!==d);t.currentDayId=t.days[0].id;save();renderAll();}}
function moveStop(i,dir){const d=day(),to=dir==='up'?i-1:i+1;if(to<0||to>=d.stops.length)return;d.autoSort=false;[d.stops[i],d.stops[to]]=[d.stops[to],d.stops[i]];save();renderDay();}
function parseGoogleMapsUrl(raw){const value=String(raw||'').trim();if(!value)return {error:'請先貼上 Google Maps 網址。'};let url;try{url=new URL(value);}catch{return {error:'這不是有效網址。'};}if(!/(^|\.)google\.|maps\.app\.goo\.gl/.test(url.hostname))return {error:'目前只支援 Google Maps 網址。'};if(url.hostname==='maps.app.goo.gl')return {mapUrl:value,error:'Google 短網址無法在瀏覽器內免費展開，請改貼完整網址。'};let lat=null,lng=null,name='';const decoded=decodeURIComponent(url.pathname.replace(/\+/g,' ')),at=decoded.match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/),bang=decoded.match(/!3d(-?\d+(?:\.\d+)?).*?!4d(-?\d+(?:\.\d+)?)/),place=decoded.match(/\/place\/([^/]+)/);if(at){lat=Number(at[1]);lng=Number(at[2]);}else if(bang){lat=Number(bang[1]);lng=Number(bang[2]);}if(place)name=place[1].replace(/\+/g,' ').trim();const query=url.searchParams.get('query')||url.searchParams.get('q')||'';if(!name&&query&&!/^-?\d+(?:\.\d+)?\s*,/.test(query))name=query;const qcoord=query.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/);if(qcoord&&lat===null){lat=Number(qcoord[1]);lng=Number(qcoord[2]);}if(!name&&lat===null)return {mapUrl:value,error:'網址中沒有可辨識的店名或座標。'};return {mapUrl:value,name,lat,lng};}
function applyGoogleMapsUrl(){const form=$('stopForm'),status=$('mapParseStatus'),result=parseGoogleMapsUrl($('mapUrlInput')?.value);if(!form||!status)return;if(result.error){status.textContent=result.error;status.dataset.tone='error';return;}if(result.name)form.elements.name.value=result.name;if(result.lat!==null&&result.lat!==undefined)form.elements.lat.value=result.lat;if(result.lng!==null&&result.lng!==undefined)form.elements.lng.value=result.lng;updateGooglePlaceLink(form.elements.name.value);status.textContent=`✓ 已回填${result.name?'店名':''}${result.lat!==null?'與座標':''}`;status.dataset.tone='success';}
function googlePlaceUrl(query=''){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([query,trip().city].filter(Boolean).join(' '))}`;}function updateGooglePlaceLink(query=''){const link=$('googlePlaceSearch');if(link)link.href=googlePlaceUrl(query);}
function openStopSheet(stop=null){const sheet=$('stopSheet'),form=$('stopForm'),moreFields=$('moreFields'),moreSettings=$('moreSettings');if(!sheet||!form)return;form.reset();editingStopId=stop?.id||null;$('sheetTitle').textContent=stop?'編輯景點':'新增景點';form.querySelector('.sheet-save').textContent=stop?'儲存修改':'儲存景點';if(stop)Object.entries(stop).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value??'';});if(moreFields)moreFields.hidden=!stop;if(moreSettings)moreSettings.textContent=stop?'收合更多設定⌃':'更多設定⌄';clearPlaceResults();updateGooglePlaceLink(stop?.name||'');sheet.hidden=false;sheet.setAttribute('aria-hidden','false');setTimeout(()=>form.elements.name?.focus(),50);}
$('parseMapLink')?.addEventListener('click',applyGoogleMapsUrl);
function closeStopSheet(){const sheet=$('stopSheet');if(!sheet)return;sheet.hidden=true;sheet.setAttribute('aria-hidden','true');editingStopId=null;clearPlaceResults();placeSearchController?.abort();}
function deleteStopWithUndo(d,s,index){const t=trip(),key=pkey(d.id,s.id),wasDone=Boolean(t.progress[key]);d.stops.splice(index,1);delete t.progress[key];save();renderDay();clearTimeout(undoTimer);pendingUndo={d,s,index,key,wasDone};const bar=$('snackbar');if(!bar)return;bar.hidden=false;bar.innerHTML=`已刪除 ${esc(s.name)} <button id="undoDelete">復原</button>`;$('undoDelete')?.addEventListener('click',undoDelete);undoTimer=setTimeout(()=>{bar.hidden=true;pendingUndo=null;},6000);}
function undoDelete(){if(!pendingUndo)return;const {d,s,index,key,wasDone}=pendingUndo;d.stops.splice(index,0,s);if(wasDone)trip().progress[key]=true;save();const bar=$('snackbar');if(bar)bar.hidden=true;clearTimeout(undoTimer);pendingUndo=null;renderDay();}
const stopForm=$('stopForm');if(stopForm)stopForm.onsubmit=e=>{e.preventDefault();const d=day(),f=new FormData(e.currentTarget),raw=Object.fromEntries(f.entries()),existing=d.stops.find(s=>s.id===editingStopId);const stop=normalizeStop({...raw,id:existing?.id||uid('stop')},d.stops.length);if(existing)Object.assign(existing,stop);else d.stops.push(stop);sortDay(d);save();closeStopSheet();renderDay();setTimeout(()=>document.querySelector(`[data-stop-id="${stop.id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),80);};const moreSettings=$('moreSettings');if(moreSettings)moreSettings.onclick=()=>{const more=$('moreFields');if(!more)return;more.hidden=!more.hidden;moreSettings.textContent=more.hidden?'更多設定⌄':'收合更多設定⌃';};document.querySelectorAll('[data-close-sheet]').forEach(el=>el.onclick=closeStopSheet);

function clearPlaceResults(message='',retry=false){const box=$('placeResults'),status=$('placeSearchStatus'),button=$('retryPlaceSearch');if(box){box.hidden=true;box.innerHTML='';}if(status)status.textContent=message;if(button)button.hidden=!retry;}
function placeLabel(properties={}){return [properties.name,properties.street,properties.district,properties.city,properties.state,properties.country].filter((v,i,a)=>v&&a.indexOf(v)===i).join(' · ');}
function guessPlaceType(properties={}){const value=`${properties.osm_value||''} ${properties.type||''}`;if(/restaurant|cafe|fast_food|food/i.test(value))return '餐飲';if(/hotel|hostel|guest_house/i.test(value))return '飯店';if(/mall|supermarket|department_store|convenience|shop/i.test(value))return '購物';if(/station|stop|platform|terminal/i.test(value))return '交通';return '景點';}
function searchAlias(query){return /唐吉[軻訶]德|唐吉/i.test(query)?`${query} ドン・キホーテ Don Quijote`:query;}
function showPlaceFeatures(features,query){const box=$('placeResults'),status=$('placeSearchStatus');if(!features.length){clearPlaceResults('找不到相符地點，可改用備援搜尋。',true);return;}box.innerHTML=features.slice(0,5).map((feature,index)=>{const p=feature.properties||{},label=placeLabel(p)||query;return `<button type="button" class="place-result" data-place-index="${index}" role="option"><b>${esc(p.name||query)}</b><small>${esc(label)}</small></button>`;}).join('');box.hidden=false;if(status)status.textContent=`找到 ${Math.min(features.length,5)} 個地點`;$('retryPlaceSearch').hidden=true;box.querySelectorAll('[data-place-index]').forEach(button=>button.onclick=()=>selectPlace(features[Number(button.dataset.placeIndex)]));}
async function searchPlaces(query){const box=$('placeResults'),status=$('placeSearchStatus'),d=day();if(!box||query.trim().length<2){clearPlaceResults();return;}placeSearchController?.abort();placeSearchController=new AbortController();if(status)status.textContent='搜尋中…';$('retryPlaceSearch').hidden=true;try{const center=d?.center||[33.5902,130.4017],params=new URLSearchParams({q:`${searchAlias(query.trim())} ${trip().city||''}`,limit:'5',lang:'zh',lat:String(center[0]),lon:String(center[1])});const response=await fetch(`https://photon.komoot.io/api/?${params}`,{signal:placeSearchController.signal});if(!response.ok)throw new Error('search failed');const data=await response.json();showPlaceFeatures(data.features||[],query);}catch(error){if(error.name!=='AbortError')clearPlaceResults('主要搜尋目前無法連線。',true);}}
async function fallbackPlaceSearch(query){if(!query||query.trim().length<2)return;const wait=1100-(Date.now()-fallbackSearchAt);if(wait>0)await new Promise(resolve=>setTimeout(resolve,wait));fallbackSearchAt=Date.now();clearPlaceResults('使用備援搜尋中…');try{const params=new URLSearchParams({format:'jsonv2',q:`${searchAlias(query.trim())} ${trip().city||''}`,limit:'5',addressdetails:'1','accept-language':'zh-TW',countrycodes:'jp'}),response=await fetch(`https://nominatim.openstreetmap.org/search?${params}`);if(!response.ok)throw new Error('fallback failed');const rows=await response.json(),features=rows.map(row=>({properties:{name:row.name||row.display_name?.split(',')[0],city:row.address?.city||row.address?.town||row.address?.village,state:row.address?.state,country:row.address?.country,osm_value:row.type},geometry:{coordinates:[Number(row.lon),Number(row.lat)]}}));showPlaceFeatures(features,query);}catch{clearPlaceResults('兩個搜尋來源都無法連線，請先手動輸入。',true);}}
function selectPlace(feature){const form=$('stopForm'),p=feature.properties||{},coordinates=feature.geometry?.coordinates||[];if(!form)return;form.elements.name.value=p.name||form.elements.name.value;form.elements.lat.value=coordinates[1]??'';form.elements.lng.value=coordinates[0]??'';form.elements.type.value=guessPlaceType(p);if(!form.elements.note.value)form.elements.note.value=placeLabel(p);clearPlaceResults('✓ 已帶入地址與座標');}
const placeSearchInput=$('placeSearchInput');if(placeSearchInput)placeSearchInput.addEventListener('input',event=>{clearTimeout(placeSearchTimer);const query=event.target.value;updateGooglePlaceLink(query);placeSearchTimer=setTimeout(()=>searchPlaces(query),450);});$('retryPlaceSearch')?.addEventListener('click',()=>fallbackPlaceSearch($('placeSearchInput')?.value||''));

let wizardStep=0;
function setWizardStep(step){wizardStep=Math.max(0,Math.min(2,step));document.querySelectorAll('[data-wizard-step]').forEach(el=>el.hidden=Number(el.dataset.wizardStep)!==wizardStep);$('wizardProgress').textContent=`步驟 ${wizardStep+1}／3`;$('wizardBack').hidden=wizardStep===0;$('wizardNext').hidden=wizardStep===2;$('wizardCreate').hidden=wizardStep!==2;}
function openTripWizard(){const modal=$('tripWizard'),form=$('tripWizardForm');form.reset();const start=new Date();start.setDate(start.getDate()+1);form.elements.startDate.value=start.toISOString().slice(0,10);form.elements.endDate.value=form.elements.startDate.value;setWizardStep(0);modal.hidden=false;modal.setAttribute('aria-hidden','false');setTimeout(()=>form.elements.title.focus(),50);}
function closeTripWizard(){const modal=$('tripWizard');modal.hidden=true;modal.setAttribute('aria-hidden','true');}
function wizardDays(startValue,endValue){const start=new Date(`${startValue}T12:00:00`),end=new Date(`${endValue}T12:00:00`),count=Math.floor((end-start)/86400000)+1;if(!Number.isFinite(count)||count<1||count>31)throw new Error('日期需為 1～31 天。');return Array.from({length:count},(_,i)=>{const date=new Date(start);date.setDate(date.getDate()+i);return normalizeDay({id:uid('day'),date:`${date.getMonth()+1}/${date.getDate()}`,title:`第 ${i+1} 天`,theme:'點擊新增景點開始安排。',stops:[]},i);});}
function createTrip(){openTripWizard();}
$('wizardNext')?.addEventListener('click',()=>{const form=$('tripWizardForm'),step=document.querySelector(`[data-wizard-step="${wizardStep}"]`);if(![...step.querySelectorAll('input')].every(input=>input.reportValidity()))return;if(wizardStep===1&&form.elements.endDate.value<form.elements.startDate.value)return alert('結束日期不能早於開始日期。');setWizardStep(wizardStep+1);});
$('wizardBack')?.addEventListener('click',()=>setWizardStep(wizardStep-1));document.querySelectorAll('[data-close-wizard]').forEach(el=>el.addEventListener('click',closeTripWizard));
$('tripWizardForm')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form).entries());let days;try{days=wizardDays(data.startDate,data.endDate);}catch(error){return alert(error.message);}const start=new Date(`${data.startDate}T12:00:00`),end=new Date(`${data.endDate}T12:00:00`),nights=Math.max(0,Math.round((end-start)/86400000));const t=normalizeTrip({id:uid('trip'),title:data.title,brandLine:`${data.city.toUpperCase()} TRIP`,subtitle:data.members||'自由規劃旅行',members:data.members,city:data.city,startDate:data.startDate,dateRange:`${start.getMonth()+1}/${start.getDate()}–${end.getMonth()+1}/${end.getDate()}`,hotel:data.hotel,nights:`${nights} 晚`,themeColor:'#173f73',days,progress:{},currentDayId:days[0].id});appData.trips.push(t);appData.currentTripId=t.id;save();closeTripWizard();switchView('scheduleView');renderAll();setAppStatus('✓ 新旅行已建立','saved',2600);});
function copyTrip(){const t=clone(trip());t.id=uid('trip');t.title=`${t.title} 副本`;t.progress={};t.days=t.days.map(d=>({...d,id:uid('day'),stops:d.stops.map(s=>({...s,id:uid('stop')}))}));t.currentDayId=t.days[0]?.id;appData.trips.push(t);appData.currentTripId=t.id;save();renderAll();}
function deleteTrip(){if(appData.trips.length<=1)return alert('至少需保留一個旅行。');if(confirm('刪除此旅行？')){appData.trips=appData.trips.filter(t=>t.id!==trip().id);appData.currentTripId=appData.trips[0].id;save();renderAll();}}
function downloadJson(name,data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function validateTrip(raw){if(!raw||typeof raw!=='object')return 'JSON 必須是旅行物件。';const ds=raw.days||raw.itinerary;if(!Array.isArray(ds)||!ds.length)return '旅行必須包含 days 陣列。';for(const [di,d] of ds.entries()){if(!Array.isArray(d.stops))return `第 ${di+1} 天缺少 stops 陣列。`;for(const [si,s] of d.stops.entries()){if(s.lat!==''||s.lng!==''){const lat=Number(s.lat),lng=Number(s.lng);if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lng)||lng<-180||lng>180)return `第 ${di+1} 天第 ${si+1} 站座標無效。`;}}}return '';}
function importJson(file){if(!file)return;const r=new FileReader();r.onload=()=>{const raw=safeJson(r.result,null);if(!raw)return alert('匯入失敗：JSON 解析失敗，現有資料未覆蓋。');if(raw.schemaVersion===SCHEMA_VERSION&&Array.isArray(raw.trips)){appData=normalizeAppData(raw);save();renderAll();return alert('完整備份匯入完成。');}const err=validateTrip(raw);if(err)return alert(`匯入失敗：${err} 現有資料未覆蓋。`);const t=normalizeTrip(raw);t.id=uid('trip');t.days=t.days.map(d=>({...d,id:uid('day'),stops:d.stops.map(s=>({...s,id:uid('stop')}))}));t.currentDayId=t.days[0].id;appData.trips.push(t);appData.currentTripId=t.id;save();renderAll();alert('旅行匯入完成。');};r.readAsText(file);}

function tripDayISO(t,d){if(!/^\d{4}-\d{2}-\d{2}$/.test(t.startDate||''))return '';const index=t.days.indexOf(d),date=new Date(`${t.startDate}T12:00:00`);date.setDate(date.getDate()+Math.max(0,index));return date.toISOString().slice(0,10);}
function weatherText(code){if(code===0)return '晴朗';if([1,2].includes(code))return '晴時多雲';if(code===3)return '陰天';if([45,48].includes(code))return '有霧';if(code>=51&&code<=67)return '下雨';if(code>=71&&code<=77)return '降雪';if(code>=80&&code<=82)return '陣雨';if(code>=95)return '雷雨';return '天氣變化';}
function renderWeather(){const t=trip(),d=day(),iso=tripDayISO(t,d),box=$('dayWeather'),record=weatherCache[t.id]?.days?.[iso];if(!box)return;if(record){box.innerHTML=`<span>🌡 ${Math.round(record.min)}–${Math.round(record.max)}°C</span><span>☔ 降雨 ${Math.round(record.rain)}%</span><span>${esc(weatherText(record.code))}</span>`;return;}const available=iso?new Date(`${iso}T12:00:00`):null;if(available)available.setDate(available.getDate()-15);const availableText=available?`${available.getMonth()+1}/${available.getDate()} 起可查看此日預報`:'請在設定填寫旅行開始日';box.innerHTML=`<span>🌤 ${availableText}</span><button type="button" id="refreshWeather">更新</button>`;$('refreshWeather')?.addEventListener('click',()=>refreshWeather(true));}
async function refreshWeather(force=false){const t=trip(),cache=weatherCache[t.id],fresh=cache&&Date.now()-cache.fetchedAt<30*60*1000;if(fresh&&!force){renderWeather();return;}if(weatherRequest)return;const centers=t.days.map(d=>d.center).filter(c=>Array.isArray(c)),lat=centers.length?centers.reduce((n,c)=>n+num(c[0]),0)/centers.length:33.5902,lng=centers.length?centers.reduce((n,c)=>n+num(c[1]),0)/centers.length:130.4017;weatherRequest=fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FTokyo&forecast_days=16`).then(r=>{if(!r.ok)throw new Error('weather');return r.json();}).then(data=>{const daily=data.daily||{},days={};(daily.time||[]).forEach((date,i)=>days[date]={code:num(daily.weather_code?.[i]),max:num(daily.temperature_2m_max?.[i]),min:num(daily.temperature_2m_min?.[i]),rain:num(daily.precipitation_probability_max?.[i])});weatherCache[t.id]={fetchedAt:Date.now(),days};localStorage.setItem(WEATHER_KEY,JSON.stringify(weatherCache));}).catch(()=>{}).finally(()=>{weatherRequest=null;renderWeather();});}

function switchView(id){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));$('hero')?.classList.toggle('hidden',id!=='homeView');const main=document.querySelector('.app-shell>main');if(main)main.scrollTo({top:0,behavior:'auto'});window.scrollTo({top:0,behavior:'auto'});if(id==='mapView')fitMap();}
function initMap(){if(!window.L){$('mapFallback').hidden=false;return;}map=L.map('map',{zoomControl:false}).setView([33.5902,130.4017],13);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);}
function updateMap(d){if(!map)return;markers.forEach(m=>map.removeLayer(m));markers=[];if(routeLine)map.removeLayer(routeLine);const pts=d.stops.filter(hasCoord).map((s,i)=>{const icon=L.divIcon({className:'',html:`<div class="number-marker">${i+1}</div>`,iconSize:[30,30],iconAnchor:[15,15]});markers.push(L.marker([s.lat,s.lng],{icon}).addTo(map).bindPopup(`<strong>${esc(s.time)}｜${esc(s.name)}</strong><br>${esc(s.note)}`));return [s.lat,s.lng];});if(pts.length){routeLine=L.polyline(pts,{color:'#2f75df',weight:4,dashArray:'7 9',opacity:.8}).addTo(map);fitMap(d);}}
function fitMap(d=day()){const pts=(d?.stops||[]).filter(hasCoord).map(s=>[Number(s.lat),Number(s.lng)]);if(map&&pts.length)setTimeout(()=>{map.invalidateSize();map.fitBounds(L.latLngBounds(pts).pad(.14));},80);}
addEventListener('online',()=>setAppStatus('✓ 已連線','saved'));addEventListener('offline',()=>setAppStatus('● 離線使用中','offline',0));if(!navigator.onLine)setTimeout(()=>setAppStatus('● 離線使用中','offline',0),0);
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('tripSelect').onchange=e=>{appData.currentTripId=e.target.value;save();renderAll();};$('newTrip').onclick=createTrip;$('copyTrip').onclick=copyTrip;$('editToggle').onclick=()=>{editMode=!editMode;localStorage.setItem(EDIT_KEY,String(editMode));$('editToggle').textContent=editMode?'完成編輯':'編輯模式';renderAll();};$('fitMap').onclick=()=>fitMap();$('importFile').onchange=e=>{importJson(e.target.files[0]);e.target.value='';};addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false;});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true;};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(reg=>{if(reg.waiting)setAppStatus('↑ 有新版可更新','update',0);reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)setAppStatus('↑ 有新版可更新','update',0);});});}).catch(()=>setAppStatus('離線功能設定失敗','error',0)));document.body.insertAdjacentHTML('beforeend','<datalist id="typeList"><option value="接送"><option value="飯店"><option value="餐飲"><option value="親子"><option value="休息"><option value="景點"><option value="地鐵"><option value="轉乘"><option value="JR"><option value="交通"><option value="購物"><option value="拍照"><option value="包車"><option value="機場"><option value="航班"><option value="備案"></datalist>');$('editToggle').textContent=editMode?'完成編輯':'編輯模式';initMap();renderAll();
