const APP_KEY='tino-travel-v4-data';
const LEGACY_ITINERARY_KEY='tino-fukuoka-trip-itinerary-v1';
const LEGACY_PROGRESS_KEY='tino-fukuoka-trip-progress-v2';
const LEGACY_CURRENT_DAY_KEY='tino-fukuoka-current-day';
const EDIT_KEY='tino-travel-edit-mode';
const SCHEMA_VERSION=4;
const ICONS={接送:'🚐',飯店:'🏨',餐飲:'🍽️',親子:'🧒',休息:'🛏️',景點:'📍',地鐵:'🚇',轉乘:'↔️',JR:'🚆',交通:'🚌',購物:'🛍️',拍照:'📸',包車:'🚐',機場:'✈️',航班:'🛫',備案:'☂️'};
const TRAVEL_MODE={接送:'driving',包車:'driving',地鐵:'transit',JR:'transit',轉乘:'transit',交通:'transit'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeJson=(text,fallback)=>{try{return JSON.parse(text)||fallback;}catch{return fallback;}};
const clone=value=>JSON.parse(JSON.stringify(value));
const num=value=>Number.isFinite(Number(value))?Number(value):0;
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const hasCoord=stop=>Number.isFinite(Number(stop?.lat))&&Number.isFinite(Number(stop?.lng))&&Number(stop.lat)>=-90&&Number(stop.lat)<=90&&Number(stop.lng)>=-180&&Number(stop.lng)<=180;
const coord=stop=>`${Number(stop.lat)},${Number(stop.lng)}`;
const progressKey=(dayId,stopId)=>`${dayId}:${stopId}`;
const now=()=>new Date().toISOString();
const isColor=value=>/^#[0-9a-f]{6}$/i.test(String(value||''));
const cleanTags=tags=>Array.isArray(tags)?tags.map(tag=>String(tag).trim()).filter(Boolean):[];
let data=loadAppData();
let editMode=localStorage.getItem(EDIT_KEY)==='true';
let map=null,markers=[],routeLine=null,deferredPrompt=null,activeView='homeView',settingsDraft=null,settingsDirty=false;

function defaultTrip(){const created=now();return normalizeTrip({tripId:'fukuoka-default',brandLine:'TINO FAMILY TRIP · FUKUOKA',tripTitle:'福岡三代同堂',tripSubtitle:'無礙動線',city:'福岡',startDate:'8/20',endDate:'8/26',partySummary:'5 大 1 小｜推車｜長輩可休｜單區規劃',tags:['8/20–8/26','6 晚同飯店','福岡'],hotelName:'三井花園飯店福岡中洲',hotelNights:'6 晚同飯店',themeColor:'#173f73',days:clone(window.DEFAULT_ITINERARY),completed:{},currentDayId:1,createdAt:created,updatedAt:created});}
function migrateLegacy(){const trip=defaultTrip();const legacy=safeJson(localStorage.getItem(LEGACY_ITINERARY_KEY),null);if(Array.isArray(legacy)&&!validateDays(legacy))trip.days=normalizeDays(legacy);const legacyProgress=safeJson(localStorage.getItem(LEGACY_PROGRESS_KEY),{});trip.completed={};for(const day of trip.days){for(const stop of day.stops){if(legacyProgress[progressKey(day.id,stop.id)]||legacyProgress[String(stop.id)]||legacyProgress[`${day.id}-${day.stops.indexOf(stop)}`])trip.completed[progressKey(day.id,stop.id)]=true;}}trip.currentDayId=validDayId(trip,localStorage.getItem(LEGACY_CURRENT_DAY_KEY))||trip.days[0]?.id||1;return {schemaVersion:SCHEMA_VERSION,activeTripId:trip.tripId,trips:[trip],createdAt:trip.createdAt,updatedAt:now(),migratedFrom:'v3'};}
function loadAppData(){const saved=safeJson(localStorage.getItem(APP_KEY),null);if(saved?.schemaVersion===SCHEMA_VERSION&&Array.isArray(saved.trips))return normalizeAppData(saved);const migrated=migrateLegacy();saveRaw(migrated);return migrated;}
function saveRaw(value){localStorage.setItem(APP_KEY,JSON.stringify(value));}
function saveApp(){data.updatedAt=now();activeTrip().updatedAt=data.updatedAt;saveRaw(data);renderAll();}
function activeTrip(){return data.trips.find(trip=>trip.tripId===data.activeTripId)||data.trips[0];}
function normalizeAppData(raw){const trips=(raw.trips||[]).map(normalizeTrip);return {schemaVersion:SCHEMA_VERSION,activeTripId:trips.some(t=>t.tripId===raw.activeTripId)?raw.activeTripId:trips[0]?.tripId,trips,createdAt:raw.createdAt||now(),updatedAt:raw.updatedAt||now()};}
function normalizeTrip(trip){const created=trip.createdAt||now(),tripId=String(trip.tripId||uid('trip'));const days=normalizeDays(trip.days||trip.itinerary||[]);return {tripId,brandLine:String(trip.brandLine||'TINO TRAVEL'),tripTitle:String(trip.tripTitle||'未命名旅行'),tripSubtitle:String(trip.tripSubtitle||'Travel Planner'),city:String(trip.city||''),startDate:String(trip.startDate||''),endDate:String(trip.endDate||''),partySummary:String(trip.partySummary||''),tags:cleanTags(trip.tags),hotelName:String(trip.hotelName||''),hotelNights:String(trip.hotelNights||''),themeColor:isColor(trip.themeColor)?String(trip.themeColor):'#173f73',days,completed:cleanCompleted(trip.completed||{},days),currentDayId:validDayId({days},trip.currentDayId)||days[0]?.id||1,createdAt:created,updatedAt:trip.updatedAt||created};}
function normalizeDays(days){const usedDays=new Set();return days.map((day,di)=>{const dayId=uniqueId(day.id||di+1,usedDays);const usedStops=new Set();return {id:Number(dayId)||dayId,date:String(day.date||''),title:String(day.title||`Day ${di+1}`),theme:String(day.theme||''),area:String(day.area||''),center:Array.isArray(day.center)?[num(day.center[0]),num(day.center[1])]:[33.5902,130.4017],stops:(day.stops||[]).map((stop,si)=>({id:uniqueId(stop.id||`d${dayId}-s${si+1}`,usedStops),time:String(stop.time||''),name:String(stop.name||'未命名景點'),type:String(stop.type||'景點'),lat:num(stop.lat),lng:num(stop.lng),note:String(stop.note||''),transport:String(stop.transport||''),duration:String(stop.duration||''),elder:String(stop.elder||''),kid:String(stop.kid||''),backup:String(stop.backup||'')}))};});}
function uniqueId(base,used){let id=String(base),i=2;while(used.has(id)){id=`${base}-${i++}`;}used.add(id);return id;}
function cleanCompleted(completed,days){const valid=new Set(days.flatMap(day=>day.stops.map(stop=>progressKey(day.id,stop.id))));return Object.fromEntries(Object.entries(completed).filter(([key,value])=>valid.has(key)&&value));}
function validDayId(trip,id){return trip.days?.some(day=>String(day.id)===String(id))?id:null;}
function validateDays(days){if(!Array.isArray(days)||!days.length)return 'days 必須是至少一天的陣列。';const dayIds=new Set();for(const [di,day] of days.entries()){if(typeof day!=='object'||!day)return `第 ${di+1} 天格式錯誤。`;if(day.id!==undefined&&day.id!==''){const id=String(day.id);if(dayIds.has(id))return `第 ${di+1} 天 day id 重複。`;dayIds.add(id);}if(!Array.isArray(day.stops))return `第 ${di+1} 天缺少 stops 陣列。`;const stopIds=new Set();for(const [si,stop] of day.stops.entries()){if(typeof stop!=='object'||!stop)return `第 ${di+1} 天第 ${si+1} 站格式錯誤。`;if(stop.id!==undefined&&stop.id!==''){const id=String(stop.id);if(stopIds.has(id))return `第 ${di+1} 天第 ${si+1} 站 stop id 重複。`;stopIds.add(id);}const lat=Number(stop.lat),lng=Number(stop.lng);if(!Number.isFinite(lat)||lat<-90||lat>90)return `第 ${di+1} 天第 ${si+1} 站緯度必須介於 -90～90。`;if(!Number.isFinite(lng)||lng<-180||lng>180)return `第 ${di+1} 天第 ${si+1} 站經度必須介於 -180～180。`;}}return '';}
function validateTrip(value){if(!value||typeof value!=='object')return '旅行專案必須是物件。';return validateDays(value.days||value.itinerary);}
function currentDay(){const trip=activeTrip();return trip.days.find(day=>String(day.id)===String(trip.currentDayId))||trip.days[0];}
function searchUrl(stop){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stop.name||coord(stop))}`;}
function routeUrl(from,to){return hasCoord(from)&&hasCoord(to)?`https://www.google.com/maps/dir/?api=1&origin=${coord(from)}&destination=${coord(to)}&travelmode=${TRAVEL_MODE[to.type]||'walking'}`:'';}
function dayRouteUrl(day){const stops=(day?.stops||[]).filter(hasCoord);return stops.length?`https://www.google.com/maps/dir/?api=1&origin=${coord(stops[0])}&destination=${coord(stops.at(-1))}&waypoints=${stops.slice(1,-1).map(coord).join('%7C')}&travelmode=transit`:'https://www.google.com/maps';}

function renderAll(){renderHero();renderHome();renderTabs();renderDay();renderSettings();document.body.classList.toggle('edit-mode',editMode);document.title=`${activeTrip()?.tripTitle||'Tino Travel'}｜Tino Travel`;}
function renderHero(){const trip=activeTrip();document.documentElement.style.setProperty('--navy',trip?.themeColor||'#173f73');$('brandLine').textContent=trip?.brandLine||'TINO TRAVEL';$('tripTitle').textContent=trip?.tripTitle||'我的旅行';$('tripSubtitle').textContent=trip?.tripSubtitle||'Travel Planner';$('partySummary').textContent=trip?.partySummary||'選擇或建立旅行專案';$('tripFacts').innerHTML=(trip?.tags?.length?trip.tags:[trip?.city,trip?.hotelNights].filter(Boolean)).map(tag=>`<span>${esc(tag)}</span>`).join('');$('editToggle').textContent=editMode?'完成':'編輯';}
function showView(id){if(settingsDirty&&!confirm('設定尚未儲存，確定離開？'))return;settingsDirty=false;activeView=id;document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.id===id));document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===id));if(id==='mapView')fitMap();window.scrollTo({top:0,behavior:'smooth'});}
function renderHome(){const trips=data.trips;$('firstUseGuide').hidden=trips.length>0;$('tripList').innerHTML=trips.map(trip=>`<article class="trip-card ${trip.tripId===data.activeTripId?'active':''}"><p class="eyebrow dark">${esc(trip.brandLine)}</p><h3>${esc(trip.tripTitle)}</h3><p>${esc(trip.tripSubtitle)}｜${esc(trip.city)}</p><div class="summary-tags">${trip.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div><div class="edit-actions"><button class="edit-btn primary" data-open-trip="${trip.tripId}">開啟</button><button class="edit-btn" data-edit-trip="${trip.tripId}">設定</button><button class="edit-btn" data-copy-trip="${trip.tripId}">複製</button><button class="edit-btn danger" data-delete-trip="${trip.tripId}">刪除</button></div></article>`).join('')||'<p class="empty-state">還沒有旅行。按下「建立新旅行」開始規劃。</p>';document.querySelectorAll('[data-open-trip]').forEach(btn=>btn.addEventListener('click',()=>{data.activeTripId=btn.dataset.openTrip;saveRaw(data);renderAll();showView('scheduleView');}));document.querySelectorAll('[data-edit-trip]').forEach(btn=>btn.addEventListener('click',()=>{data.activeTripId=btn.dataset.editTrip;settingsDraft=null;saveRaw(data);renderAll();showView('settingsView');}));document.querySelectorAll('[data-copy-trip]').forEach(btn=>btn.addEventListener('click',()=>copyTrip(btn.dataset.copyTrip)));document.querySelectorAll('[data-delete-trip]').forEach(btn=>btn.addEventListener('click',()=>deleteTrip(btn.dataset.deleteTrip)));}
function renderTabs(){const trip=activeTrip();$('dayTabs').innerHTML=(trip?.days||[]).map((day,index)=>`<button class="day-tab ${String(day.id)===String(trip.currentDayId)?'active':''}" data-day="${day.id}"><b>Day ${index+1}</b><small>${esc((day.date||'').split(' ')[0])}</small></button>`).join('')+(editMode?'<button class="day-tab add-day" id="addDay">＋新增</button>':'');document.querySelectorAll('.day-tab[data-day]').forEach(btn=>btn.addEventListener('click',()=>{trip.currentDayId=btn.dataset.day;saveApp();showView('scheduleView');}));$('addDay')?.addEventListener('click',addDay);}
function renderDay(){const trip=activeTrip(),day=currentDay();if(!trip||!day)return;const done=day.stops.filter(stop=>trip.completed[progressKey(day.id,stop.id)]).length,pct=day.stops.length?Math.round(done/day.stops.length*100):0;$('daySummary').innerHTML=`<article class="summary-card"><div class="summary-top"><div><p class="date-line">${esc(day.date)} · DAY ${trip.days.indexOf(day)+1}${day.area?` · ${esc(day.area)}`:''}</p><h2>${esc(day.title)}</h2></div><div class="progress-ring" style="--progress:${pct}%"><b>${pct}%</b></div></div><p class="theme">${esc(day.theme)}</p><div class="summary-tags"><span>📍 ${day.stops.length} 站</span><span>♿ 長輩可休</span><span>👶 推車優先</span><span>☂ 雨天可刪減</span></div>${editMode?dayEditor(day,trip):''}</article>`;$('timeline').innerHTML=day.stops.map((stop,index)=>stopCard(day,stop,index)).join('')||(editMode?'<p class="empty-state">目前沒有景點，請新增第一站。</p>':'');bindScheduleEvents(day);$('openDayMap').href=dayRouteUrl(day);updateMap(day);}
function dayEditor(day,trip){const index=trip.days.indexOf(day);return `<div class="editor-panel day-editor"><label>日期<input data-day-field="date" value="${esc(day.date)}"></label><label>每日主題<input data-day-field="title" value="${esc(day.title)}"></label><label>區域<input data-day-field="area" value="${esc(day.area)}"></label><label class="wide">說明<textarea data-day-field="theme">${esc(day.theme)}</textarea></label><div class="edit-actions"><button class="edit-btn primary" id="addStop">＋新增景點</button><button class="edit-btn" data-copy-day>複製本日</button><button class="edit-btn" data-move-day="up" ${index===0?'disabled':''}>↑ 日</button><button class="edit-btn" data-move-day="down" ${index===trip.days.length-1?'disabled':''}>↓ 日</button><button class="edit-btn danger" id="deleteDay">刪除本日</button></div></div>`;}
function stopCard(day,stop,index){const trip=activeTrip(),prior=day.stops[index-1],isDone=Boolean(trip.completed[progressKey(day.id,stop.id)]);return `<article class="stop-card ${isDone?'done':''}" data-index="${index}"><div class="stop-icon">${ICONS[stop.type]||'•'}</div><div class="stop-header"><div><div class="stop-time">${esc(stop.time)} <span class="stop-type">｜${esc(stop.type)}</span></div><h3 class="stop-name">${esc(stop.name)}</h3></div><button class="complete" data-complete="${stop.id}">✓</button></div><p class="stop-note">${esc(stop.note)}</p>${index?`<div class="travel-note">${TRAVEL_MODE[stop.type]==='transit'?'🚇':TRAVEL_MODE[stop.type]==='driving'?'🚐':'🚶'} ${esc(stop.transport||'從上一站前往')} ${stop.duration?`· ${esc(stop.duration)}`:'· 依現場班次與體力調整'}</div>`:''}<div class="badges"><span class="badge elder">長輩｜${esc(stop.elder)}</span><span class="badge kid">嘟嘟｜${esc(stop.kid)}</span>${stop.backup?`<span class="badge backup">備案｜${esc(stop.backup)}</span>`:''}</div><div class="actions"><a class="action map" href="${searchUrl(stop)}" target="_blank" rel="noopener">📍 查看地點</a>${prior&&routeUrl(prior,stop)?`<a class="action route" href="${routeUrl(prior,stop)}" target="_blank" rel="noopener">🧭 從上一站導航</a>`:''}</div>${editMode?stopEditor(stop,index,day.stops.length):''}</article>`;}
function stopEditor(stop,index,total){const input=(f,label,type='text')=>`<label>${label}<input ${type==='number'?'inputmode="decimal"':''} data-stop-field="${f}" value="${esc(stop[f])}"></label>`;return `<div class="editor-panel stop-editor">${input('time','時間')}${input('name','名稱')}<label>類型<input list="typeList" data-stop-field="type" value="${esc(stop.type)}"></label>${input('transport','交通方式')}${input('duration','移動時間')}${input('lat','緯度','number')}${input('lng','經度','number')}<label class="wide">說明<textarea data-stop-field="note">${esc(stop.note)}</textarea></label><label>長輩提醒<input data-stop-field="elder" value="${esc(stop.elder)}"></label><label>幼兒提醒<input data-stop-field="kid" value="${esc(stop.kid)}"></label><label class="wide">備案<input data-stop-field="backup" value="${esc(stop.backup)}"></label><div class="edit-actions"><button class="edit-btn" data-copy-stop>複製</button><button class="edit-btn" data-move="up" ${index===0?'disabled':''}>↑ 上移</button><button class="edit-btn" data-move="down" ${index===total-1?'disabled':''}>↓ 下移</button><button class="edit-btn danger" data-delete-stop>刪除</button></div></div>`;}
function bindScheduleEvents(day){const trip=activeTrip();document.querySelectorAll('[data-complete]').forEach(btn=>btn.addEventListener('click',()=>{const item=progressKey(day.id,btn.dataset.complete);trip.completed[item]=!trip.completed[item];if(!trip.completed[item])delete trip.completed[item];saveApp();}));if(!editMode)return;document.querySelectorAll('[data-day-field]').forEach(el=>el.addEventListener('input',()=>{day[el.dataset.dayField]=el.value;saveApp();}));$('addStop')?.addEventListener('click',()=>{day.stops.push({id:uid('stop'),time:'',name:'新景點',type:'景點',lat:day.center[0],lng:day.center[1],note:'',transport:'',duration:'',elder:'',kid:'',backup:''});saveApp();});$('deleteDay')?.addEventListener('click',deleteDay);document.querySelector('[data-copy-day]')?.addEventListener('click',copyDay);document.querySelectorAll('[data-move-day]').forEach(btn=>btn.addEventListener('click',()=>moveDay(btn.dataset.moveDay)));document.querySelectorAll('.stop-card').forEach(card=>{const stop=day.stops[Number(card.dataset.index)];card.querySelectorAll('[data-stop-field]').forEach(el=>el.addEventListener('change',()=>{stop[el.dataset.stopField]=['lat','lng'].includes(el.dataset.stopField)?num(el.value):el.value;saveApp();}));card.querySelector('[data-copy-stop]')?.addEventListener('click',()=>{day.stops.splice(Number(card.dataset.index)+1,0,{...clone(stop),id:uid('stop'),name:`${stop.name} 複製`});saveApp();});card.querySelector('[data-delete-stop]')?.addEventListener('click',()=>{if(confirm('刪除此景點？')){const [removed]=day.stops.splice(Number(card.dataset.index),1);delete trip.completed[progressKey(day.id,removed.id)];saveApp();}});card.querySelectorAll('[data-move]').forEach(btn=>btn.addEventListener('click',()=>moveStop(day,Number(card.dataset.index),btn.dataset.move)));});}
function addDay(){const trip=activeTrip(),id=uid('day');trip.days.push({id,date:'新日期',title:'新行程日',theme:'請輸入今日主題。',area:'',center:[33.5902,130.4017],stops:[]});trip.currentDayId=id;saveApp();}
function deleteDay(){const trip=activeTrip(),day=currentDay();if(trip.days.length<=1)return alert('至少需保留一天。');if(confirm('刪除本日與所有景點？')&&confirm('再次確認：此日行程與完成紀錄都會刪除。')){day.stops.forEach(stop=>delete trip.completed[progressKey(day.id,stop.id)]);const index=trip.days.indexOf(day);trip.days.splice(index,1);trip.currentDayId=trip.days[Math.max(0,index-1)]?.id||trip.days[0].id;saveApp();}}
function copyDay(){const trip=activeTrip(),day=currentDay(),copy=clone(day);copy.id=uid('day');copy.title=`${day.title} 複製`;copy.stops=copy.stops.map(stop=>({...stop,id:uid('stop')}));trip.days.splice(trip.days.indexOf(day)+1,0,copy);trip.currentDayId=copy.id;saveApp();}
function moveDay(dir){const trip=activeTrip(),day=currentDay(),from=trip.days.indexOf(day),to=dir==='up'?from-1:from+1;if(to<0||to>=trip.days.length)return;[trip.days[from],trip.days[to]]=[trip.days[to],trip.days[from]];saveApp();}
function moveStop(day,index,dir){const to=dir==='up'?index-1:index+1;if(to<0||to>=day.stops.length)return;[day.stops[index],day.stops[to]]=[day.stops[to],day.stops[index]];saveApp();}

function renderSettings(){const trip=activeTrip();settingsDraft=settingsDraft||clone(trip);$('tripSettings').innerHTML=`<article class="summary-card"><div class="summary-top"><div><p class="eyebrow dark">TRIP SETTINGS</p><h2>旅行設定</h2></div><button class="edit-btn" id="backHome">返回</button></div><div class="settings-preview" id="settingsPreview" style="--preview:${esc(settingsDraft.themeColor)}"><p id="previewBrand">${esc(settingsDraft.brandLine)}</p><h3><span id="previewTitle">${esc(settingsDraft.tripTitle)}</span>｜<span id="previewSubtitle">${esc(settingsDraft.tripSubtitle)}</span></h3><small id="previewParty">${esc(settingsDraft.partySummary)}</small><div class="summary-tags" id="previewTags">${settingsDraft.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></div><div class="editor-panel"><label>品牌列<input data-trip-field="brandLine" value="${esc(settingsDraft.brandLine)}"></label><label>主標題<input data-trip-field="tripTitle" value="${esc(settingsDraft.tripTitle)}"></label><label>副標題<input data-trip-field="tripSubtitle" value="${esc(settingsDraft.tripSubtitle)}"></label><label>成員摘要<input data-trip-field="partySummary" value="${esc(settingsDraft.partySummary)}"></label><label>城市<input data-trip-field="city" value="${esc(settingsDraft.city)}"></label><label>開始日期<input data-trip-field="startDate" value="${esc(settingsDraft.startDate)}"></label><label>結束日期<input data-trip-field="endDate" value="${esc(settingsDraft.endDate)}"></label><label>飯店<input data-trip-field="hotelName" value="${esc(settingsDraft.hotelName)}"></label><label>住宿晚數<input data-trip-field="hotelNights" value="${esc(settingsDraft.hotelNights)}"></label><label>主題顏色<input type="color" data-trip-field="themeColor" value="${esc(settingsDraft.themeColor)}"></label><label class="wide">標籤（逗號分隔）<input data-trip-field="tags" value="${esc(settingsDraft.tags.join('、'))}"></label><div class="edit-actions"><button class="edit-btn primary" id="saveSettings">儲存設定</button><button class="edit-btn" id="cancelSettings">取消</button></div></div></article>`;document.querySelectorAll('[data-trip-field]').forEach(input=>input.addEventListener('input',()=>{settingsDirty=true;settingsDraft[input.dataset.tripField]=input.dataset.tripField==='tags'?cleanTags(input.value.split(/[、,]/)):input.value;updateSettingsPreview();}));$('saveSettings')?.addEventListener('click',()=>{settingsDraft.tags=cleanTags(settingsDraft.tags);settingsDraft.themeColor=isColor(settingsDraft.themeColor)?settingsDraft.themeColor:'#173f73';Object.assign(trip,settingsDraft,{updatedAt:now()});settingsDirty=false;settingsDraft=null;saveApp();});$('cancelSettings')?.addEventListener('click',()=>{settingsDirty=false;settingsDraft=null;renderSettings();});$('backHome')?.addEventListener('click',()=>showView('homeView'));}
function updateSettingsPreview(){if(!$('settingsPreview')||!settingsDraft)return;$('settingsPreview').style.setProperty('--preview',isColor(settingsDraft.themeColor)?settingsDraft.themeColor:'#173f73');$('previewBrand').textContent=settingsDraft.brandLine;$('previewTitle').textContent=settingsDraft.tripTitle;$('previewSubtitle').textContent=settingsDraft.tripSubtitle;$('previewParty').textContent=settingsDraft.partySummary;$('previewTags').innerHTML=cleanTags(settingsDraft.tags).map(tag=>`<span>${esc(tag)}</span>`).join('');}
function createTrip(){const base=defaultTrip();Object.assign(base,{tripId:uid('trip'),brandLine:'TINO TRAVEL',tripTitle:'新旅行',tripSubtitle:'Travel Planner',city:'',startDate:'',endDate:'',partySummary:'',tags:['新旅行'],hotelName:'',hotelNights:'',days:[{id:1,date:'Day 1',title:'第一天',theme:'開始規劃今日行程。',area:'',center:[33.5902,130.4017],stops:[]}],completed:{},currentDayId:1,createdAt:now(),updatedAt:now()});data.trips.push(base);data.activeTripId=base.tripId;settingsDraft=clone(base);settingsDirty=false;saveRaw(data);renderAll();showView('settingsView');}
function copyTrip(id){const source=data.trips.find(t=>t.tripId===id);if(!source)return;const copy=clone(source);copy.tripId=uid('trip');copy.tripTitle=`${source.tripTitle} 複製`;copy.days=copy.days.map(day=>({...day,id:uid('day'),stops:day.stops.map(stop=>({...stop,id:uid('stop')}))}));copy.currentDayId=copy.days[0]?.id||1;copy.completed={};copy.createdAt=now();copy.updatedAt=copy.createdAt;data.trips.push(copy);data.activeTripId=copy.tripId;saveApp();showView('homeView');}
function deleteTrip(id){const trip=data.trips.find(t=>t.tripId===id);if(!trip)return;if(data.trips.length<=1)return alert('至少需保留一個旅行。');if(confirm(`刪除「${trip.tripTitle}」？`)&&confirm('再次確認：旅行專案與完成紀錄都會刪除。')){data.trips=data.trips.filter(t=>t.tripId!==id);data.activeTripId=data.trips[0].tripId;saveApp();showView('homeView');}}
function exportJson(){downloadJson(activeTrip(),`${activeTrip().tripTitle||'trip'}.json`);}
function backupAll(){downloadJson(data,'tino-travel-backup.json');}
function downloadJson(payload,name){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function importJson(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{const parsed=safeJson(reader.result,null);let next=null,error='JSON 解析失敗。';if(parsed?.schemaVersion===SCHEMA_VERSION&&Array.isArray(parsed.trips)){const normalized=normalizeAppData(parsed);error=normalized.trips.length?'':'備份檔沒有旅行。';if(!error)next=normalized;}else{error=validateTrip(parsed);if(!error){const trip=normalizeTrip({...parsed,tripId:parsed.tripId||uid('trip'),createdAt:parsed.createdAt||now(),updatedAt:now()});next=clone(data);const existing=next.trips.findIndex(t=>t.tripId===trip.tripId);if(existing>=0)trip.tripId=uid('trip');next.trips.push(trip);next.activeTripId=trip.tripId;}}if(error)return alert(`匯入失敗：${error}`);data=next;saveApp();showView('homeView');alert('匯入完成。');};reader.readAsText(file);}
function restoreDefault(){if(confirm('恢復預設福岡旅行？會新增一份乾淨的福岡專案，不覆蓋其他旅行。')){const trip=defaultTrip();trip.tripId=uid('trip');data.trips.push(trip);data.activeTripId=trip.tripId;saveApp();showView('scheduleView');}}
function resetProgress(){const trip=activeTrip();if(confirm('清除本旅行所有完成紀錄？')){trip.completed={};saveApp();}}

function initMap(){if(!window.L){$('mapFallback').hidden=false;return;}map=L.map('map',{zoomControl:false}).setView([33.5902,130.4017],13);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);}
function updateMap(day){if(!map)return;markers.forEach(m=>map.removeLayer(m));markers=[];if(routeLine)map.removeLayer(routeLine);const points=(day?.stops||[]).filter(hasCoord).map((stop,index)=>{const icon=L.divIcon({className:'',html:`<div class="number-marker">${index+1}</div>`,iconSize:[30,30],iconAnchor:[15,15]});markers.push(L.marker([Number(stop.lat),Number(stop.lng)],{icon}).addTo(map).bindPopup(`<strong>${esc(stop.time)}｜${esc(stop.name)}</strong><br>${esc(stop.note)}`));return [Number(stop.lat),Number(stop.lng)];});if(points.length){routeLine=L.polyline(points,{color:'#2f75df',weight:4,dashArray:'7 9',opacity:.8}).addTo(map);fitMap(day);}}
function fitMap(day=currentDay()){const points=(day?.stops||[]).filter(hasCoord).map(s=>[Number(s.lat),Number(s.lng)]);if(map&&points.length)setTimeout(()=>{map.invalidateSize();map.fitBounds(L.latLngBounds(points).pad(.14));},80);}

document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));
$('createTrip').addEventListener('click',createTrip);
$('fitMap').addEventListener('click',()=>fitMap());
$('resetProgress').addEventListener('click',resetProgress);
$('editToggle').addEventListener('click',()=>{editMode=!editMode;localStorage.setItem(EDIT_KEY,String(editMode));renderAll();});
$('exportJson').addEventListener('click',exportJson);
$('backupAll').addEventListener('click',backupAll);
$('importJson').addEventListener('click',()=>$('importFile').click());
$('importFile').addEventListener('change',event=>{importJson(event.target.files[0]);event.target.value='';});
$('restoreDefault').addEventListener('click',restoreDefault);
addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;$('installBtn').hidden=false;});
$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true;});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
document.body.insertAdjacentHTML('beforeend','<datalist id="typeList"><option value="接送"><option value="飯店"><option value="餐飲"><option value="親子"><option value="休息"><option value="景點"><option value="地鐵"><option value="轉乘"><option value="JR"><option value="交通"><option value="購物"><option value="拍照"><option value="包車"><option value="機場"><option value="航班"><option value="備案"></datalist>');
initMap();renderAll();showView('homeView');
